data_dir: ../../../msd-splits/dataset
msu_dir: ../../../MSU/dataset
framework: contrastive
arch: transformer
workers: 4
epochs: 200
warmup_epochs: 0
start_epoch: 0
batch_size: 64
world_size: 1
lr: 0.0005
min_lr: 1.0e-09
seed: null
gpu: 1
print_freq: 100
duration: 9.91
sr: 16000
num_chunks: 8
mel_dim: 128
n_fft: 1024
win_length: 1024
frontend: cnn
mix_type: cf
audio_rep: mel
text_type: bert
text_rep: stochastic
cos: true
attention_nlayers: 4
attention_ndim: 256
text_backbone: bert-base-uncased
probe_type: mlp
mlp_dim: 512
eval_dataset: fma
dropout: 0
is_norm: 1
l2_weight_decay: 0
